### PR TITLE
support Spark3.3

### PR DESCRIPTION
**Pull request by qidi1**
### What problem does this PR solve? 

support spark 3.3
### What is changed and how it works?
1. Add spark-3.3 profile
2. Add Spark-3.3 module in spark-wrapper and add Code in spark-3.3
3. Fix the code in spark-core to be compatible with spark3.0 3.1 3.2 3.3
     * Change the pattern matching in `SetCatalogAndNamespace` because the parament become `ResolvedNamespace` and `ResolvedDBObjectName`.
     * Add method `dropNamespace(strings: Array[String])` in `TiCatalog` for spark3.3 change the parament of `dropNamespace` in `SupportsNamespaces`
     * Add method `parseQuery` in `TiParser` for spark3.3 add `parserQuery` in `ParserInterface`.
5. Update `log4j-api`  and `log4j-core` version to 2.17.2 and exclude it in other dependencies. or you will get java.lang.NoSuchMethodError: org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.setImmediateFlush in spark3.3
6. Exclude slf4j-log4j12 dependency  hadoop-client or you will find multiple bindings of  `Log4jLoggerFactory` on the classpath
7. Update assembly to package spark-3.3 in spark wrapper
8. Fix some tests

### Check List 

Tests 
1. IT
 * /run-all-tests profile=spark-3.3.0
 * /run-all-tests profile=spark-3.2.2
 * /run-all-tests profile=spark-3.1.3
 * /run-all-tests (spark 3.0.3)
 * /run-all-tests profile=spark 3.3.0 tidb = v5.3.0 tikv = v5.3.0 pd = v5.3.0
3. Use Test
 * Package TiSpark with 3.0.3 and work with spark 3.0.3
 * Package TiSpark with 3.1.3 and work with spark 3.1.3
 * Package TiSpark with 3.2.2 and work with spark 3.2.2
 * Package TiSpark with 3.3.0 and work with spark 3.3.0

### CODE REVIEW

**Comment by qidi1** [comment]
/run-all-tests profile=spark 3.3.0 tidb = v5.3.0 tikv = v5.3.0 pd = v5.3.0

File: pom.xml [hunk 1]
```diff
@@ -196,6 +197,17 @@
                 <spark.version.release>3.2</spark.version.release>
             </properties>
         </profile>
+        <profile>
+            <id>spark-3.3.0</id>
```
Comment (pan3793) [inline pom.xml:201]: why not name it `spark-3.3`? will it be updated if bump 3.3.1 in future?

Comment (qidi1) [reply pom.xml:201]: > why not name it `spark-3.3`? will it be updated if bump 3.3.1 in future?

yes, It will update to 3.3.1 in the future.

File: core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala [hunk 2]
```diff
@@ -48,19 +43,19 @@ class TelemetrySuite extends SharedSQLContext {
...
     val tiSparkTeleInfo = TiSparkTeleInfo.getTiSparkTeleInfo()
     assert(!tiSparkTeleInfo.get("tidb_version").contains("UNKNOWN"))
   }
+  test("test cacheInvalidateCallback does not work ") {
+    val conf = TiConfiguration.createDefault("127.0.0.1:2379")
+    val tiSession: TiSession = TiSession.getInstance(conf);
+    CacheInvalidateListener.initCacheListener(
+      _sparkSession.sparkContext,
+      tiSession.getRegionManager)
+    // it's to late to inject
```
Comment (shiyuhang0) [inline core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala:56]:
```suggestion
    // it's too late to inject
```

File: core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala [hunk 3]
```diff
@@ -48,19 +43,19 @@ class TelemetrySuite extends SharedSQLContext {
...
-      val teleMsg = new TeleMsg(_sparkSession)
-      telemetry.report(teleMsg)
-    }
-  }
-
   test("test get TiDB version") {
     val tiSparkTeleInfo = TiSparkTeleInfo.getTiSparkTeleInfo()
     assert(!tiSparkTeleInfo.get("tidb_version").contains("UNKNOWN"))
   }
+  test("test cacheInvalidateCallback does not work ") {
```
Comment (shiyuhang0) [inline core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala:50]: what is this test for

File: pom.xml [hunk 4]
```diff
@@ -170,12 +170,13 @@
...
         <module>spark-wrapper/spark-3.1</module>
         <module>spark-wrapper/spark-3.2</module>
+        <module>spark-wrapper/spark-3.3</module>
         <module>assembly</module>
     </modules>
 
     <profiles>
         <profile>
-            <id>spark-3.1.1</id>
+            <id>spark-3.1.3</id>
```
Comment (shiyuhang0) [inline pom.xml:179]: plz change Daily CI as well, I suggest we just use major.minor like 3.1. so we need not change Daily CI every time

File: core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala [hunk 5]
```diff
@@ -48,19 +43,19 @@ class TelemetrySuite extends SharedSQLContext {
...
 
-  test("test telemetry") {
-    noException should be thrownBy {
-      val telemetry = new Telemetry
-      telemetry.setUrl("http://127.0.0.1:8091/test")
-      val teleMsg = new TeleMsg(_sparkSession)
-      telemetry.report(teleMsg)
-    }
-  }
-
```
Comment (Daemonxiao) [inline core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala:59]: Why delete this test?

Comment (qidi1) [reply core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala]: Sorry delete this code is error operator.

File: core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala (hunk 3 above)
Comment (qidi1) [reply core/src/test/scala/com/pingcap/tispark/telemetry/TelemetrySuite.scala]: It not for this pr,It should be delete but I delete error code.

File: pom.xml (hunk 4 above)
Comment (qidi1) [reply pom.xml:179]: I think using `3.1.3` will remind us exactly what version of Spark we are using for the adaptation.

Comment (pan3793) [reply pom.xml:179]: There is less opportunity that Spark to make major changes in the patch version, +1 for `spark-3.1`

File: spark-wrapper/spark-3.3/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/TiBasicLogicalPlan.scala [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+
+import com.pingcap.tispark.auth.TiAuthorization
+import org.apache.spark.sql.catalyst.analysis.{ResolvedDBObjectName, ResolvedNamespace}
+
+object TiBasicLogicalPlan {
+  def verifyAuthorizationRule(
+      logicalPlan: LogicalPlan,
+      tiAuthorization: Option[TiAuthorization]): LogicalPlan = {
+    logicalPlan match {
+      case st @ SetCatalogAndNamespace(namespace) =>
```
Comment (xuanyu66) [inline spark-wrapper/spark-3.3/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/TiBasicLogicalPlan.scala:27]: After [this PR](https://github.com/pingcap/tispark/pull/2489) merged, we need to check whether it is `tidb_catalog`

**Review by xuanyu66 — CHANGES_REQUESTED** [review]
Also we should update the user doc

**Comment by qidi1** [comment]
> Also we should update the user doc

I changed

**Review by shiyuhang0 — APPROVED** [review]

**Review by xuanyu66 — APPROVED** [review]

**Review by Daemonxiao — APPROVED** [review]

**Review by xuanyu66 — APPROVED** [review]

**Comment by qidi1** [comment]
/run-all-tests profile=spark 3.3.0 tidb = v5.3.0 tikv = v5.3.0 pd = v5.3.0

**Review by xuanyu66 — APPROVED** [review]
